// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcfbaseEByVxKb-PckZk6-R9QwEvIgJc',
    appId: '1:701527012547:web:48824398a1a54959e19e76',
    messagingSenderId: '701527012547',
    projectId: 'projet-france-b3aca',
    authDomain: 'projet-france-b3aca.firebaseapp.com',
    storageBucket: 'projet-france-b3aca.firebasestorage.app',
    measurementId: 'G-MKF8YSY69E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9cJO4Ou67y1vIeJUBPADNPAoD0LKXS98',
    appId: '1:701527012547:android:c807c906bd69f0f7e19e76',
    messagingSenderId: '701527012547',
    projectId: 'projet-france-b3aca',
    storageBucket: 'projet-france-b3aca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQf3EBK6sroBDXUT4I1cLCzDuhybyZA48',
    appId: '1:701527012547:ios:4369ade330edf911e19e76',
    messagingSenderId: '701527012547',
    projectId: 'projet-france-b3aca',
    storageBucket: 'projet-france-b3aca.firebasestorage.app',
    iosBundleId: 'com.example.projetParcourFrance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQf3EBK6sroBDXUT4I1cLCzDuhybyZA48',
    appId: '1:701527012547:ios:4369ade330edf911e19e76',
    messagingSenderId: '701527012547',
    projectId: 'projet-france-b3aca',
    storageBucket: 'projet-france-b3aca.firebasestorage.app',
    iosBundleId: 'com.example.projetParcourFrance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkcfbaseEByVxKb-PckZk6-R9QwEvIgJc',
    appId: '1:701527012547:web:3200b43d9c1b359ce19e76',
    messagingSenderId: '701527012547',
    projectId: 'projet-france-b3aca',
    authDomain: 'projet-france-b3aca.firebaseapp.com',
    storageBucket: 'projet-france-b3aca.firebasestorage.app',
    measurementId: 'G-YGYFLRVGZG',
  );
}
